name: 🛠️ Ajustos i millores
description: Apanyos genèrics que ens trobem pel camí
title: "[AJUSTOS] "
labels: ["🛠️ ajustos-millores"]
body:

   - type: input
    id: date
    attributes:
      label: Data
      placeholder: YYYY-MM-DD
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasques
      description: Com va dir Jack el Desembudellador...
      placeholder: |
        ## Cabecera
        - [ ] Añadir espacio gestionable para banners en cabecera

  - type: dropdown
    id: effort
    attributes:
      label: Temps previst
      options:
        - 10 min
        - 15 min
        - 30 min
        - 1h
        - 2h
        - 4h
        - 8h
        - "+ 8h (10 minuts comercials)"

  - type: checkboxes
    id: billing
    attributes:
      label: Facturación
      options:
        - label: Facturable
        - label: Correcció